@startuml
Title 経路探索フローチャート

(*) --> "開始"

-down-> ===マップ生成方法チェック===

if  マップの生成方法を決める
 -->[壁伸ばし法] ===経路探索方法チェック===
else
 ---->[穴掘り法] ===経路探索方法チェック===
endif

if 経路探索の方法を決める
 -->[ダイクストラ法] ===マップ生成===
else
 ---->[ベルマンフォード法] ===マップ生成===
else
 ---->[A*法] ===マップ生成===
endif

-->"終了"
--> (*)

@enduml